window.EVOLUTION = {
  config: {
    nome: "Evolution Escola Técnica",
    whatsapp: "5588992049096",
    whatsappExibicao: "(88) 9 9204-9096",
    telefone: "(88) 3621-6644",
    instagram: "evolutioneducacao",
    endereco: "R. Zeferino Veras, 80 - Centro, Camocim-CE",
    enderecoRef: "Em frente à Praça do Coreto, nas instalações do Colégio Impacto",
    mapaBusca: "R. Zeferino Veras, 80, Centro, Camocim - CE",
    horario: "",
    email: "",
    formados: 4000,
    desde: 2017
  },


  promocao: {
    ativa: true,
    texto: "Matrícula grátis no Técnico em Radiologia!",
    detalhe: "Vagas limitadas, garanta a sua.",
    curso: "radiologia"
  },

  imagens: {
    hero: "",
    sobre: ""
  },

  galeria: [
    { titulo: "Aulas práticas em laboratório", icone: "estetoscopio", imagem: "" },
    { titulo: "Visita técnica à Policlínica", icone: "predio", imagem: "" },
    { titulo: "Vacinação com os alunos", icone: "seringa", imagem: "" },
    { titulo: "Cerimônia do Jaleco", icone: "jaleco", imagem: "" },
    { titulo: "Ação Saúde do Idoso", icone: "maos", imagem: "" },
    { titulo: "Outubro Rosa", icone: "fita", imagem: "" }
  ],

  professores: [
    { nome: "Adriele", area: "Radiologia", foto: "" },
    { nome: "Helena", area: "Biossegurança", foto: "" },
    { nome: "Aluízio", area: "", foto: "" }
  ],


  depoimentos: [],

  faq: [
    { p: "Quais são os pré-requisitos para os cursos técnicos?", r: "Os cursos técnicos exigem escolaridade mínima de ensino médio (cursando ou concluído, conforme o curso). Fale com a gente no WhatsApp para confirmar a situação do seu histórico." },
    { p: "Quanto tempo duram os cursos?", r: "Depende do curso. Os técnicos têm duração mais longa, com estágio; os cursos livres vão de algumas horas a poucos meses. Punção Venosa, por exemplo, tem 3 meses (100 h). Veja a duração na página de cada curso." },
    { p: "Tem estágio?", r: "Sim. Nos cursos técnicos você faz estágio em ações reais de saúde, hospitais e clínicas, além de visitas técnicas como a da Policlínica." },
    { p: "Recebo certificado?", r: "Sim, todos os cursos concluídos dão direito a certificado." },
    { p: "Quais são as formas de pagamento?", r: "Trabalhamos com matrícula + mensalidade, e sempre tem condição especial rolando. Chame no WhatsApp para saber o valor e a promoção do mês." },
    { p: "Moro em Granja, Barroquinha ou outra cidade da região. Vale a pena?", r: "Vale! Já formamos alunos de toda a região. Temos turma aos sábados (integral), que facilita para quem vem de fora." }
  ],

  cursos: [
    {
      slug: "enfermagem",
      nome: "Técnico em Enfermagem",
      tipo: "tecnico",
      status: "aberta",
      icone: "estetoscopio",
      imagem: "",
      resumo: "A formação mais procurada da saúde, com prática desde o início e estágio.",
      frase: "Escolha a turma que cabe na sua rotina: semanal (segundas e quartas) ou aos sábados.",
      duracao: "Consulte",
      cargaHoraria: "",
      turmas: ["Turma semanal: segundas e quartas", "Turma de sábado: integral"],
      preco: null,
      promocao: "",
      destaques: ["Turma semanal ou aos sábados", "Estágio com vacinação e ações de saúde", "Aulas práticas em laboratório"],
      oQueFaz: "O técnico em enfermagem cuida diretamente do paciente: administra medicamentos, faz curativos, verifica sinais vitais, aplica vacinas e auxilia o enfermeiro nos procedimentos, sempre com segurança e humanização.",
      ondeTrabalha: ["Hospitais e UPAs", "Postos de saúde e PSF", "Clínicas e consultórios", "Home care", "Salas de vacina"],
      modulos: ["Anatomia e Fisiologia", "Fundamentos de Enfermagem", "Farmacologia e cálculo de medicação", "Saúde Coletiva e Imunização", "Clínica Médica e Cirúrgica", "Saúde da Mulher e da Criança", "Urgência e Emergência", "Biossegurança"],
      estagio: "Estágio supervisionado em serviços de saúde, incluindo ações de vacinação com a comunidade.",
      preRequisitos: "Ensino médio (cursando ou concluído). Consulte as condições."
    },
    {
      slug: "radiologia",
      nome: "Técnico em Radiologia",
      tipo: "tecnico",
      status: "aberta",
      icone: "raiox",
      imagem: "",
      resumo: "Mais que um curso, é o seu futuro! O curso técnico mais rápido, com estágio em hospitais e clínicas.",
      frase: "Seu futuro na Radiologia começa agora. Dê o primeiro passo rumo a uma profissão em alta.",
      duracao: "Consulte",
      cargaHoraria: "",
      turmas: ["Consulte os horários da próxima turma"],
      preco: null,
      promocao: "Matrícula grátis",
      destaques: ["Curso técnico mais rápido", "Estágio em hospitais e clínicas", "Piso de 2 salários mínimos + 40% de insalubridade", "Visita técnica à Policlínica"],
      oQueFaz: "O técnico em radiologia opera os equipamentos de diagnóstico por imagem (raio-X, tomografia, mamografia e outros), posicionando o paciente e garantindo exames de qualidade com total proteção radiológica.",
      ondeTrabalha: ["Hospitais", "Clínicas de diagnóstico por imagem", "Policlínicas", "Clínicas odontológicas", "Indústria (radiologia industrial)"],
      modulos: ["Anatomia radiológica", "Física das radiações", "Proteção radiológica", "Técnicas radiológicas", "Tomografia e mamografia", "Processamento e qualidade de imagem", "Ética e legislação"],
      estagio: "Estágio em hospitais e clínicas, além de visita técnica à Policlínica.",
      preRequisitos: "Ensino médio (cursando ou concluído). Consulte as condições."
    },
    {
      slug: "seguranca-do-trabalho",
      nome: "Técnico em Segurança do Trabalho",
      tipo: "tecnico",
      status: "em-breve",
      icone: "capacete",
      imagem: "",
      resumo: "Prevenção de acidentes e saúde do trabalhador, com foco no setor industrial.",
      frase: "Uma profissão exigida por lei nas empresas e cada vez mais valorizada.",
      duracao: "Consulte",
      cargaHoraria: "",
      turmas: ["Consulte a próxima turma"],
      preco: null,
      promocao: "",
      destaques: ["Visitas técnicas", "Foco no setor industrial", "Profissão exigida pelas normas regulamentadoras"],
      oQueFaz: "O técnico em segurança do trabalho identifica riscos, orienta o uso de EPIs, faz inspeções, treina equipes e ajuda a empresa a cumprir as Normas Regulamentadoras (NRs), prevenindo acidentes e doenças ocupacionais.",
      ondeTrabalha: ["Indústrias", "Construção civil", "Empresas de todos os portes", "Consultorias de SST", "Órgãos públicos"],
      modulos: ["Normas Regulamentadoras (NRs)", "Higiene ocupacional", "Prevenção e combate a incêndio", "Primeiros socorros", "Ergonomia", "Gestão de riscos", "Legislação trabalhista e previdenciária"],
      estagio: "Visitas técnicas e estágio com foco no setor industrial.",
      preRequisitos: "Ensino médio (cursando ou concluído). Consulte as condições."
    },
    {
      slug: "puncao-venosa",
      nome: "Punção Venosa e Administração de Medicamentos",
      tipo: "livre",
      status: "aberta",
      icone: "seringa",
      imagem: "",
      resumo: "Aprenda na prática, adquira mais segurança e se destaque no mercado de trabalho.",
      frase: "Aprenda na prática, adquira mais segurança e se destaque no mercado de trabalho.",
      duracao: "3 meses",
      cargaHoraria: "100 h",
      turmas: ["Domingos, das 8h30 às 14h30"],
      preco: "R$ 225/mês",
      precoDetalhe: "Matrícula R$ 99,90 + mensalidade R$ 225",
      promocao: "",
      destaques: ["Aulas aos domingos", "100 h de carga horária", "Muita prática"],
      oQueFaz: "Capacita você a realizar punção venosa e administrar medicamentos pelas diversas vias com técnica correta e segurança para o paciente. Uma habilidade muito cobrada em hospitais, clínicas e farmácias.",
      ondeTrabalha: ["Hospitais e UPAs", "Clínicas", "Laboratórios de análises", "Home care", "Farmácias"],
      modulos: ["Anatomia do sistema venoso", "Técnicas de punção venosa periférica", "Vias de administração de medicamentos", "Cálculo de medicação e gotejamento", "Biossegurança e descarte", "Prática supervisionada"],
      estagio: "Aulas práticas supervisionadas durante todo o curso.",
      preRequisitos: "Indicado para estudantes e profissionais da saúde. Consulte."
    },
    {
      slug: "urgencia-emergencia-obstetrica",
      nome: "Urgência e Emergência Obstétrica",
      tipo: "livre",
      status: "aberta",
      icone: "bebe",
      imagem: "",
      resumo: "Curso rápido de 10 horas para agir com segurança nas emergências da gestação e do parto.",
      frase: "Saiba o que fazer nos momentos que mais importam.",
      duracao: "10 h",
      cargaHoraria: "10 h",
      turmas: ["Consulte a data da próxima turma"],
      preco: "R$ 65",
      promocao: "Desconto para gestantes",
      destaques: ["Apenas 10 horas", "Desconto para gestantes", "Certificado"],
      oQueFaz: "Prepara profissionais e estudantes para reconhecer e atuar nas principais urgências obstétricas, do atendimento inicial à gestante até o apoio no parto de emergência.",
      ondeTrabalha: ["Maternidades", "UPAs e hospitais", "Atendimento pré-hospitalar", "Unidades básicas de saúde"],
      modulos: ["Avaliação inicial da gestante", "Principais emergências obstétricas", "Parto de emergência", "Cuidados com o recém-nascido"],
      estagio: "Conteúdo com simulações práticas.",
      preRequisitos: "Aberto a estudantes, profissionais da saúde e gestantes."
    },
    {
      slug: "atendente-de-farmacia",
      nome: "Atendente de Farmácia",
      tipo: "livre",
      status: "aberta",
      icone: "capsula",
      imagem: "",
      resumo: "Entre no mercado das farmácias, incluindo técnicas de ambulatório farmacêutico.",
      frase: "Vagas limitadas. As aulas acontecem às segundas.",
      duracao: "Consulte",
      cargaHoraria: "",
      turmas: ["Aulas às segundas-feiras"],
      preco: null,
      promocao: "Vagas limitadas",
      destaques: ["Aulas às segundas", "Técnicas de ambulatório farmacêutico", "Vagas limitadas"],
      oQueFaz: "O atendente de farmácia atende o cliente no balcão, organiza e controla o estoque, confere receitas junto ao farmacêutico e apoia serviços de ambulatório, como aferição de pressão e aplicação de injetáveis.",
      ondeTrabalha: ["Farmácias e drogarias", "Farmácias de manipulação", "Distribuidoras de medicamentos", "Farmácias hospitalares"],
      modulos: ["Atendimento ao cliente", "Noções de farmacologia", "Leitura de receitas", "Controle de estoque", "Técnicas de ambulatório farmacêutico", "Legislação farmacêutica"],
      estagio: "Aulas práticas de ambulatório farmacêutico.",
      preRequisitos: "Consulte."
    },
    {
      slug: "aph",
      nome: "APH - Atendimento Pré-Hospitalar",
      tipo: "livre",
      status: "em-breve",
      icone: "pulso",
      imagem: "",
      resumo: "Primeiro atendimento a vítimas de acidentes e emergências, antes da chegada ao hospital.",
      frase: "Cada minuto conta. Esteja preparado para salvar vidas.",
      duracao: "Consulte",
      cargaHoraria: "",
      turmas: ["Consulte a próxima turma"],
      preco: null,
      promocao: "",
      destaques: ["Simulações práticas", "Suporte básico de vida", "Certificado"],
      oQueFaz: "Ensina a avaliar a cena e a vítima, realizar suporte básico de vida, imobilizações e transporte seguro em situações de urgência e emergência.",
      ondeTrabalha: ["Serviços de resgate e SAMU", "Brigadas de emergência", "Eventos", "Empresas e indústrias"],
      modulos: ["Avaliação da cena e da vítima", "Suporte básico de vida (RCP)", "Hemorragias e choque", "Imobilização e transporte", "Traumas"],
      estagio: "Simulações práticas de atendimento.",
      preRequisitos: "Consulte."
    },
    {
      slug: "libras",
      nome: "Libras - Pacote Básico",
      tipo: "livre",
      status: "em-breve",
      icone: "mao",
      imagem: "",
      resumo: "Aprenda a Língua Brasileira de Sinais e torne seu atendimento mais inclusivo.",
      frase: "Comunicação que inclui.",
      duracao: "3 meses",
      cargaHoraria: "",
      turmas: ["Segundas-feiras"],
      preco: null,
      promocao: "",
      destaques: ["3 meses", "Aulas às segundas", "Certificado"],
      oQueFaz: "Introduz a Libras para que você consiga se comunicar com pessoas surdas no dia a dia e no trabalho. Um diferencial em qualquer atendimento ao público, especialmente na saúde.",
      ondeTrabalha: ["Atendimento em saúde", "Escolas", "Órgãos públicos", "Comércio e serviços"],
      modulos: ["Alfabeto manual e números", "Saudações e apresentações", "Vocabulário do cotidiano", "Estrutura gramatical básica", "Cultura surda"],
      estagio: "",
      preRequisitos: "Aberto a todos."
    },
    {
      slug: "instrumentacao-cirurgica",
      nome: "Instrumentação Cirúrgica",
      tipo: "especializacao",
      status: "em-breve",
      icone: "tesoura",
      imagem: "",
      resumo: "Especialização para quem já é técnico em enfermagem e quer atuar no centro cirúrgico.",
      frase: "Dê o próximo passo na sua carreira: o centro cirúrgico.",
      duracao: "Consulte",
      cargaHoraria: "",
      turmas: ["Consulte a próxima turma"],
      preco: null,
      promocao: "",
      destaques: ["Para técnicos em enfermagem", "Atuação em centro cirúrgico", "Certificado"],
      oQueFaz: "O instrumentador cirúrgico prepara, organiza e fornece os instrumentais à equipe durante a cirurgia, garantindo agilidade e técnica asséptica.",
      ondeTrabalha: ["Centros cirúrgicos", "Hospitais", "Clínicas cirúrgicas", "Centrais de material e esterilização"],
      modulos: ["Instrumentais cirúrgicos", "Técnica asséptica", "Tempos cirúrgicos", "Montagem de mesa", "Central de material e esterilização"],
      estagio: "Consulte.",
      preRequisitos: "Ter concluído o Técnico em Enfermagem."
    }
  ]
};
